GET http://localhost:3000/aa




###

POST  http://localhost:3000/
Content-Type: application/json
{
    "name" : "seas",
    "email" : "aaaa",
    "password" : "passoifuu",
    "image" : "asd",
}


###

POST  https://chat-backend-mreh.onrender.com/
Content-Type: application/json
{
    "name" : "bac",
    "email" : "abc",
    "password" : "abc",
    "image" : "abc",
}
